zn "%SYS"
set password=$system.Util.GetEnviron("VECTOR_ADMIN_SYSTEM_PASSWORD")
if password="" { write !,"VECTOR_PASSWORD_FAILED",! halt }
kill properties set properties("Password")=password,properties("ChangePassword")=0,properties("PasswordNeverExpires")=1
set sc=##class(Security.Users).Modify("_SYSTEM",.properties)
if $system.Status.IsError(sc) { do $system.Status.DisplayError(sc) halt }
write !,"VECTOR_PASSWORD_OK",!
halt
